---
- name: install dependencies
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items:
    - gcc
    - make
    - libc6-dev
  when: ansible_os_family == "Debian"

- name: install dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make
  when: ansible_os_family == "RedHat"

- name: install dependencies
  zypper:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make
  when: ansible_os_family == 'Suse'