---
- name: Create log and local directories
  file: path={{item}} state=directory owner={{user_name}} group={{group_name}} mode=755
  with_items:
    - "{{log_home}}/haproxy"

- name: Install HAProxy
  apt: name=haproxy state=present

- name: Configure HAProxy
  template: dest="/etc/haproxy.cfg" owner={{user_name}} group={{group_name}} src=haproxy.cfg.j2
  when: (neo4j_deploy_ha_mode == True and install_neo4j == True)
