---
#### Global settings ####

host_address: "{{ansible_default_ipv4.address}}"
root_dir: /opt
cluster_path: mindmaps/cluster
cluster_home: "{{root_dir}}/{{cluster_path}}"
resource_home: /opt/mindmaps/resources
log_home : "/var/log/{{cluster_path}}"

#user and group running the cluster
user_name: mindmaps
group_name: mindmaps

#### Cassandra settings ####

cassandra_version: 3.2.1
cassandra_mirror: "http://www.eu.apache.org/dist/cassandra/{{cassandra_version}}"
cassandra_tarball_name: "apache-cassandra-{{cassandra_version}}-bin.tar.gz"

cassandra_host_address: "{{host_address}}"
cassandra_listen_address: "{{cassandra_host_address}}"
cassandra_rpc_address: "{{cassandra_host_address}}"

cassandra_num_tokens: 256

cassandra_hosts: ["{{cassandra_host_address}}"]
cassandra_seeds: ["{{cassandra_host_address}}"]
cassandra_read_consistency: ONE
cassandra_write_consistency: ALL

cassandra_data_dir: /var/lib/cassandra/data
cassandra_commitlog_dir: /var/lib/cassandra/commitlog
cassandra_saved_caches_dir: /var/lib/cassandra/saved_caches

#ports
cassandra_storage_port: 7000
cassandra_ssl_storage_port: 7001
cassandra_native_transport_port: 9042
cassandra_rpc_port: 9160

#ulimit configuration
ulimit_config: 
      - domain: "{{user_name}}"
        type: '-'
        item: memlock
        value: unlimited
      - domain: "{{user_name}}"
        type: '-'
        item: nofile
        value: 100000
      - domain: "{{user_name}}"
        type: '-'
        item: nproc
        value: 32768
      - domain: "{{user_name}}"
        type: '-'
        item: as
        value: unlimited

#Default limits.conf location
ulimit_config_location: /etc/security/limits.conf
