---
- name: Core cluster deployment on core node
  hosts: core-servers
  remote_user: kasper
  sudo: yes
  vars:
    supervised_processes: [zk, storm, cassandra, es]

  roles:
     - common
     - zk
     - storm
     - cassandra
     - es
     - supervisor
