---
- name: Core cluster deployment on GM node
  hosts: graph-servers
  remote_user: kasper
  sudo: yes
  vars:
    supervised_processes: [zk, storm, cassandra, es, redis]

  roles:
     - common
     - zk
     - storm
     - cassandra
     - es	
     - redis
     - supervisor
