---
- name: mindmaps-local-cluster
  hosts: 127.0.0.1
  vars:
    cluster_home: /opt/mindmaps/cluster
    log_home: /var/log/mindmaps/cluster
    storm_daemons: [nimbus, supervisor, ui, drpc]
  remote_user: root
  sudo: yes
  
  roles:
     - common
     - zk
     - storm
     - cassandra
     - es
     - supervisor
