---
- name: mindmaps-local-cluster
  hosts: core-servers
  vars:
    cluster_home: /opt/mindmaps/cluster
    log_home: /var/log/mindmaps/cluster
    storm_daemons: [nimbus, supervisor, ui, drpc]

  remote_user: root
  roles:
     #- common
     #- zk
     #- storm
     #- cassandra
     - es
     #- supervisor
