---
- name: Create ElasticSearch log and local directories
  file: path={{item}} state=directory owner={{user_name}} group={{group_name}} mode=755
  with_items:
    - "{{elasticsearch_log_dir}}"
    - "{{elasticsearch_data_dir}}"
    - "{{elasticsearch_work_dir}}"

# Sort out dependencies
- name: Install packages
  apt: name={{item}} state=present
  with_items:
       - curl
       - htop
       - ntp
       - unzip

- name: Fetch ElasticSearch package
  get_url: dest={{cluster_home}} url={{elasticsearch_download_url}}/{{elasticsearch_tarball_name}} owner={{user_name}} group={{group_name}}

- name: Uncompress ElasticSearch package
  unarchive: copy=no  dest={{cluster_home}} src="{{cluster_home}}/{{elasticsearch_tarball_name}}" owner={{user_name}} group={{group_name}}

- name: Remove archive
  file: path="{{cluster_home}}/{{elasticsearch_tarball_name}}" state=absent

- name: Rename
  command: mv {{cluster_home}}/elasticsearch-{{elasticsearch_version}} {{cluster_home}}/elasticsearch

- name: Configure Elasticsearch properties
  template: dest="{{elasticsearch_home_dir}}/config/elasticsearch.yml" owner={{user_name}} group={{group_name}} src=elasticsearch.yml.j2

- name: Create temp dir for config
  file: path="{{resource_home}}/conf/temp" state=directory owner={{user_name}} group={{group_name}} mode=755

- name: Copy Titan-Cassandra properties
  command: cp {{resource_home}}/conf/titan-cassandra.properties {{resource_home}}/conf/temp/titan-cassandra.properties
  #copy: src="{{resource_home}}/conf/titan-cassandra.properties" dest="{{resource_home}}/conf/temp/titan-cassandra.properties" owner={{user_name}} group={{group_name}} mode=755

- name: Configure Titan-Cassandra-Elasticsearch properties
  template: dest="{{resource_home}}/conf/temp/titan-cassandra-es.properties" owner={{user_name}} group={{group_name}} src=titan-cassandra-es.properties.j2 owner={{user_name}} group={{group_name}} mode=755

- name: Merge Titan-Cassandra-Elasticsearch properties
  assemble: src="{{resource_home}}/conf/temp" dest="{{resource_home}}/conf/titan-cassandra-es.properties" owner={{user_name}} group={{group_name}} mode=755

- name: Remove temp dir for config
  file: path="{{resource_home}}/conf/temp" state=absent





  
