---
- name: Create ZK log and local directories
  file: path={{item}} state=directory owner={{user_name}} group={{group_name}} mode=755
  with_items:
    #- "{{cluster_home}}/zookeeper"
    - "{{log_home}}/zookeeper"

- name: Fetch ZK package
  get_url: dest={{cluster_home}} url={{zk_mirror}}/{{zk_tarball_name}} owner={{user_name}} group={{group_name}}
  
- name: Uncompress the ZK tar
  unarchive: copy=no  dest={{cluster_home}} src="{{cluster_home}}/{{zk_tarball_name}}" owner={{user_name}} group={{group_name}}

- name: Remove ZK tar
  file: path="{{cluster_home}}/{{zk_tarball_name}}" state=absent

- name: Mv to server
  command: mv {{cluster_home}}/zookeeper-{{zk_version}} {{cluster_home}}/zookeeper

- name: Set ZK server dir
  set_fact: zookeeper_server_dir="{{cluster_home}}/zookeeper"

- name: Configure ZK
  template: dest="{{zookeeper_server_dir}}/conf/zoo.cfg" owner={{user_name}} group={{group_name}} src=zoo.cfg.j2

- name: Add myid file
  template: dest="{{zookeeper_server_dir}}/myid" owner={{user_name}} group={{group_name}} src=myid.j2

