---

cluster_home: /opt/mindmaps/cluster
resource_home: /opt/mindmaps/resources
log_home: /var/log/mindmaps/cluster

zk_version: 3.4.6
zookeeper_client_port: 2181
zookeeper_hosts: [ core-plx122, core-plx123, gm-plx133 ]

storm_version: 0.10.0
storm_local_dir: "{{cluster_home}}/storm/local"
storm_log_dir: "{{log_home}}/storm" 
storm_nimbus_host: gm-plx133
storm_nimbus_seeds: [ gm-plx133 ]
storm_drpc_hosts: [ gm-plx133 ]

storm_drpc_extra_config:
    drpc.request.timeout.secs: 300
    drpc.max_buffer_size: 1048576
    drpc.childopts: "-Xmx1g"
storm_worker_extra_config:   
    worker.childopts: -Xmx64g
storm_nimbus_extra_config:
    nimbus.childopts: "-Xmx4g "
    nimbus.task.timeout.secs: 300
    nimbus.supervisor.timeout.secs: 300
storm_supervisor_extra_config:
    supervisor.childopts: "-Xmx64g "
    supervisor.worker.timeout.secs: 300
storm_topology_extra_config:
    topology.acker.executors: 1
    topology.debug: false
    topology.message.timeout.secs: 300

storm_ui_port: 8081
storm_ui_extra_config:
    ui.childopts: "-Xmx768m"
storm_worker_extra_config:
    worker.childopts: "-Xmx4g -XX:+UseConcMarkSweepGC -Dcom.sun.management.jmxremote"

database: cassandra
cassandra_version: 2.1.9
cassandra_num_tokens: 256
cassandra_hosts: [ core-plx122, core-plx123, gm-plx133 ]
cassandra_seeds: [ core-plx123, gm-plx133 ]
cassandra_read_consistency: ONE
cassandra_write_consistency: ALL
cassandra_replication_factor: "{{cassandra_hosts | length }}"
cassandra_dir: /var/lib/cassandra
cassandra_data_dir: "{{cassandra_dir}}/data"
cassandra_commitlog_dir: "{{cassandra_dir}}/commitlog"
cassandra_saved_caches_dir: "{{cassandra_dir}}/saved_caches"
cassandra_hints_dir : "{{cassandra_dir}}/hints"


