---

- name: Ensure ownership
  file: path={{item}} owner={{user_name}} group={{group_name}} recurse=yes
  with_items:
       - "{{cluster_home}}"
       - "{{log_home}}"

- include: install_supervisor.yml

