---
#### Global settings ####

host_address: "{{ansible_default_ipv4.address}}"
root_dir: /opt
cluster_path: mindmaps/cluster
cluster_home: "{{root_dir}}/{{cluster_path}}"
resource_home: /opt/mindmaps/resources
log_home : "/var/log/{{cluster_path}}"

#user and group running the cluster
user_name: mindmaps
group_name: mindmaps

#### Redis Ansible Variables ####

redis_user: "{{user_name}}"
redis_group: "{{group_name}}"
redis_download_url: http://download.redis.io/releases
redis_version: 3.0.7
redis_tarball_name: "redis-{{redis_version}}.tar.gz"

redis_home_dir: "{{cluster_home}}/redis"
redis_log_dir: "{{log_home}}/redis"
redis_logfile: "{{redis_log_dir}}/redis.log"
redis_data_dir: /var/lib/redis

#### General ####

redis_roles: [master, slave]

redis_master_host: "{{host_address}}"
redis_master_port: 6379
redis_slave_host:  "{{host_address}}"
redis_slave_port: 6380

redis_daemonize: "no"                                                          
redis_master_pidfile: /var/run/redis/{{ redis_master_port }}.pid
redis_slave_pidfile: /var/run/redis/{{ redis_slave_port }}.pid

# You might want to use 0.0.0.0 and then allow access from your app servers or
# anything that needs to talk to redis by configuring redis_server_allow below.
redis_bind: ["{{host_address}}"]

# Allow connections from a list of hosts, you may use masks such as:
# 192.168.0.0/16 but it must be in a list, ex. ['192.168.0.0/16'].
redis_server_allow: ["{{host_address}}"]

redis_timeout: 0
redis_tcp_keepalive: 0
redis_tcp_backlog: 511
redis_loglevel: 'notice'

redis_databases: 16

#### Snapshotting ####

#Snapshotting settings for slave.
redis_save:
  - 900 1
  - 300 10
  - 60 10000

redis_rdbcompression: 'yes'
redis_rdbchecksum: 'yes'
redis_dbfilename: snapshot.rdb
redis_stop_writes_on_bgsave_error: 'yes'
redis_dbdir: "{{redis_data_dir}}"

#### Replication ####

redis_slave_serve_stale_data: 'no'
redis_slave_read_only: 'yes'
redis_repl_disable_tcp_nodelay: 'no'
redis_repl_ping_slave_period: 10
redis_repl_timeout: 60
redis_repl_backlog_size: 1mb
redis_repl_backlog_ttl: 3600
redis_slave_priority: 100
redis_min_slaves_to_write: 0
redis_min_slaves_max_lag: 10


#### Limits ####

redis_maxclients: 10000

# Set a percent multiplier to cap the amount of RAM redis will use. For example
# if you wanted to limit it to 80% of the total RAM you would input 0.8.
redis_maxmemory_multiplier: 0.1

redis_maxmemory: 50000000000
redis_maxmemory_policy: 'volatile-lru'
redis_maxmemory_samples: 5

#### Append only mode ####

redis_appendfilename: "appendonly.aof"
redis_appendfsync: always
redis_no_appendfsync_on_rewrite: 'no'
redis_auto_aof_rewrite_percentage: 100
redis_auto_aof_rewrite_min_size: 64mb


##### LUA SCRIPTING  #####
redis_lua_time_limit: 5000


#### Slow log ####

redis_slowlog_log_slower_than: 10000
redis_slowlog_max_len: 128

#### Latency monitor ####

redis_latency_monitor_threshold: 0




