---
# Sort out dependencies
- name: Install packages
  apt: name={{item}} state=present
  with_items:
       - make
       - autotools-dev
       - autoconf
       - git
       - software-properties-common
       - python-software-properties
       - libtool
       - uuid-dev
       - tar
       - gzip

- name: Install ZeroMQ
  apt: name={{item}} state=present
  with_items:
       - build-essential
       - libzmq3-dev

