---

#### STORM settings ####

storm_version: 0.10.0
storm_mirror: "http://mirror.catn.com/pub/apache/storm/apache-storm-{{storm_version}}"
storm_tarball_name: "apache-storm-{{storm_version}}.tar.gz"

storm_nimbus_host: "{{host_address}}"
storm_nimbus_seeds: ["{{host_address}}"]
storm_drpc_hosts: ["{{host_address}}"]

nimbus_thrift_port: 6627
storm_java_library_path: "/usr/local/lib:/opt/local/lib:/usr/lib"
storm_zookeeper_hosts: ["{{host_address}}"]
storm_zookeeper_port: "{{zookeeper_client_port}}"

storm_drpc_extra_config:
    drpc.request.timeout.secs: 300
storm_nimbus_extra_config:
    nimbus.childopts: "-Xmx4g "
    nimbus.task.timeout.secs: 300
    nimbus.supervisor.timeout.secs: 300
storm_supervisor_extra_config:
    supervisor.childopts: "-Xmx4g "
    supervisor.worker.timeout.secs: 300
storm_topology_extra_config:
    topology.acker.executors: 1
    topology.debug: false
    topology.message.timeout.secs: 300

storm_transactional_extra_config:
    transactional.zookeeper.port: "{{ storm_zookeeper_port }}"
    transactional.zookeeper.root: "/storm-transactional"

storm_ui_port: 8081
storm_ui_extra_config:
    ui.childopts: "-Xmx768m"
storm_worker_extra_config:
    worker.childopts: "-Xmx4g -XX:+UseConcMarkSweepGC -Dcom.sun.management.jmxremote"
storm_worker_ports: [6700, 6701, 6702, 6703]
storm_zookeeper_extra_config:
    storm.zookeeper.port:  "{{ storm_zookeeper_port }}"
    storm.zookeeper.retry.interval: 5000
    storm.zookeeper.retry.times: 60
    storm.zookeeper.root: "/storm"
    storm.zookeeper.session.timeout: 3000
